# SwiftLint Configuration for vet.tn iOS Project

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Xcode handles this
  - line_length  # We'll use a more lenient limit

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Included paths (relative to the project root)
included:
  - vet.tn

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - vet.tn/Assets.xcassets
  - vet.tn/vet_tn.xcdatamodeld

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"

